#docker-compose -f common.yml -f kafka-cluster.yml up
#docker-compose -f common.yml -f services.yml up
#docker run -it --network=host confluentinc/cp-kafkacat kafkacat -L -b localhost:19092
version: '3.7'
networks:
  application:
    driver: bridge