twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  hello-twitter: Hello Twitter
  twitter-v2:
    enabled: false
    base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=create_at&expansions=author_id
    rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
    bearer-token: ${TWITTER_BEARER_TOKEN}
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
